"""Static pinned-board probe.

Most of the provably dead guesses in the pilot were made *after* the
dictionary had already collapsed to a single consistent word (RESEARCH_NOTES.md,
section 1). At that point the game has no decision left: the board plus the
excluded letters determine a common English word, and the only thing to do is
name it. This module isolates that regime from the game loop.

A *pinned board* is a (board, excluded letters, word) triple such that exactly
one dictionary word is consistent with the board and the exclusions. Boards
are generated by playing the greedy reference policy against a word until the
candidate set is a singleton, which yields the kind of state a competent
player actually reaches. The ``pinned_probe`` task then shows each board as a
single prompt with no tool loop and asks for the word.

Three things are scored per board:

- ``exact``          the answer is the target.
- ``consistent``     the answer fits the board and exclusions at all. A wrong
                     but consistent answer is a dictionary-coverage mismatch
                     (the model found a word the reference dictionary lacks);
                     an inconsistent one is a verification failure.
- ``in_dictionary``  the answer is a word of the reference dictionary.

Only the standard library is used for generation so the task can be built from
a bare install; the Inspect pieces sit at the bottom of the module.
"""

from __future__ import annotations

import csv
import hashlib
import pathlib
import random
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from typing import Any, Literal

from inspect_ai import Task, task
from inspect_ai.dataset import MemoryDataset, Sample
from inspect_ai.scorer import Score, Scorer, Target, mean, scorer, stderr
from inspect_ai.solver import TaskState, generate

from hangman_bench.datasets import Language, get_alphabet
from hangman_bench.oracle import (
    Chooser,
    choose_max_hit_probability,
    consistent_candidates,
    load_dictionary_index,
    resolve_wordlist,
    reveal,
)

BoardStyle = Literal["spaced", "contiguous"]

# Word lengths of the original dataset; the probe samples the same range so
# its boards look like the ones the models faced in the game.
DEFAULT_LENGTHS: tuple[int, ...] = (5, 6, 7, 8, 9, 10)


@dataclass(frozen=True)
class PinnedBoard:
    """A board state whose consistent candidate set is exactly one word."""

    word: str
    board: str  # '.' for unrevealed, as ``oracle.reveal`` renders it
    excluded: str  # wrong letters guessed so far, sorted
    source: str = "dictionary"  # where the board came from: dictionary | pilot
    zipf_band: str = ""  # common | moderate | rare, when a frequency source was available

    @property
    def guessed(self) -> frozenset[str]:
        return frozenset({ch for ch in self.board if ch != "."} | set(self.excluded))

    @property
    def revealed_fraction(self) -> float:
        return sum(1 for ch in self.board if ch != ".") / len(self.board)

    def render(self, style: BoardStyle = "spaced") -> str:
        """The board as the model sees it: '_' for unrevealed letters."""
        cells = [ch if ch != "." else "_" for ch in self.board]
        return " ".join(cells) if style == "spaced" else "".join(cells)


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------


def pinned_board_for(
    word: str,
    dictionary: Sequence[str],
    chooser: Chooser = choose_max_hit_probability,
    extra_wrong: int = 0,
    rng: random.Random | None = None,
    alphabet: str | None = None,
) -> PinnedBoard | None:
    """Play ``chooser`` against ``word`` until the candidate set is a singleton.

    Returns the board at that moment, or None when the word is only ever
    pinned once fully revealed (so there is nothing left to name). With
    ``extra_wrong`` > 0, that many further letters absent from the word are
    added to the exclusions; they cannot change a singleton candidate set,
    but they make the board look like one reached by a weaker player.
    """
    word = word.lower()
    letters = alphabet or "abcdefghijklmnopqrstuvwxyz"
    if word not in dictionary:
        return None
    guessed: list[str] = []
    while True:
        board = reveal(word, guessed)
        if "." not in board:
            return None
        candidates = consistent_candidates(board, guessed, dictionary)
        if len(candidates) == 1:
            break
        letter = chooser(candidates, frozenset(guessed))
        if letter is None:
            return None
        guessed.append(letter)

    excluded = {g for g in guessed if g not in word}
    if extra_wrong > 0:
        pool = sorted(set(letters) - set(word) - excluded)
        picker = rng if rng is not None else random.Random(0)
        excluded.update(picker.sample(pool, min(extra_wrong, len(pool))))
    return PinnedBoard(word=word, board=board, excluded="".join(sorted(excluded)))


def _seed_material(seed: int, words: Sequence[str], spec: str) -> int:
    """RNG seed derived from the dictionary content, not its file order."""
    digest = hashlib.sha256()
    digest.update(f"{seed}|{spec}|".encode())
    for w in words:
        digest.update(w.encode())
        digest.update(b"\n")
    return int.from_bytes(digest.digest()[:8], "big")


def sample_pinned_boards(
    index: dict[int, list[str]],
    n: int,
    seed: int = 0,
    lengths: Iterable[int] = DEFAULT_LENGTHS,
    extra_wrong: int = 0,
    band_of: Any = None,
    bands: Sequence[str] = (),
) -> list[PinnedBoard]:
    """Draw ``n`` pinned boards from a length-indexed dictionary, seeded.

    Boards are stratified evenly across ``lengths`` and, when ``band_of`` is
    given (a callable word -> band label) and ``bands`` names the labels,
    evenly across bands within each length. The draw depends only on the
    sorted dictionary contents, the seed, and the strata spec, so a rebuild
    that changes file order does not change the sample.
    """
    lengths = tuple(lengths)
    per_length = n // len(lengths) + (1 if n % len(lengths) else 0)
    all_words = sorted(w for length in lengths for w in index.get(length, []))
    spec = f"lengths={lengths};extra_wrong={extra_wrong};bands={','.join(bands)}"
    rng = random.Random(_seed_material(seed, all_words, spec))

    out: list[PinnedBoard] = []
    for length in lengths:
        words = sorted(index.get(length, []))
        rng.shuffle(words)
        quota: dict[str, int] = {}
        if bands:
            share = per_length // len(bands) + (1 if per_length % len(bands) else 0)
            quota = dict.fromkeys(bands, share)
        else:
            quota = {"": per_length}
        taken: dict[str, int] = dict.fromkeys(quota, 0)
        for word in words:
            if all(taken[b] >= quota[b] for b in quota):
                break
            band = band_of(word) if band_of is not None else ""
            if band not in quota or taken[band] >= quota[band]:
                continue
            board = pinned_board_for(word, words, extra_wrong=extra_wrong, rng=rng)
            if board is None:
                continue
            out.append(PinnedBoard(board.word, board.board, board.excluded, "dictionary", band))
            taken[band] += 1
    return out[:n]


# --------------------------------------------------------------------------
# TSV round trip
# --------------------------------------------------------------------------

TSV_FIELDS = ["word", "board", "excluded", "source", "zipf_band"]


def write_boards(boards: Sequence[PinnedBoard], path: pathlib.Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=TSV_FIELDS, delimiter="\t")
        writer.writeheader()
        for b in boards:
            writer.writerow(
                {
                    "word": b.word,
                    "board": b.board,
                    "excluded": b.excluded,
                    "source": b.source,
                    "zipf_band": b.zipf_band,
                }
            )


def read_boards(path: pathlib.Path) -> list[PinnedBoard]:
    """Read boards from a TSV; extra columns are ignored."""
    with path.open(newline="", encoding="utf-8") as handle:
        rows = csv.DictReader(handle, delimiter="\t")
        return [
            PinnedBoard(
                word=row["word"],
                board=row["board"],
                excluded=row.get("excluded", "") or "",
                source=row.get("source", "") or "",
                zipf_band=row.get("zipf_band", "") or "",
            )
            for row in rows
        ]


# --------------------------------------------------------------------------
# Scoring
# --------------------------------------------------------------------------


def parse_answer(completion: str, length: int, alphabet: str) -> str:
    """The word the model answered with.

    Prefers the last token of the target length, since a model that explains
    itself usually ends on its answer; falls back to the last alphabetic token.
    """
    tokens = [t for t in re.findall(r"[^\W\d_]+", completion.lower()) if set(t) <= set(alphabet)]
    if not tokens:
        return ""
    sized = [t for t in tokens if len(t) == length]
    return sized[-1] if sized else tokens[-1]


def is_consistent(answer: str, board: PinnedBoard) -> bool:
    """Whether ``answer`` fits the board and the excluded letters."""
    if len(answer) != len(board.board):
        return False
    return consistent_candidates(board.board, board.guessed, [answer]) == [answer]


@scorer(
    metrics={
        "exact": [mean(), stderr()],
        "consistent": [mean(), stderr()],
        "in_dictionary": [mean()],
    }
)
def probe_scorer(wordlist: str | None = None) -> Scorer:
    """Score a pinned-board answer: exact, consistent with the board, in the dictionary."""
    wordlist_path = str(resolve_wordlist(wordlist))

    async def score(state: TaskState, target: Target) -> Score:
        metadata: dict[str, Any] = state.metadata or {}
        board = PinnedBoard(
            word=str(metadata["word"]),
            board=str(metadata["board"]),
            excluded=str(metadata.get("excluded", "")),
        )
        alphabet = get_alphabet(Language(metadata.get("language", Language.ENGLISH.value)))
        answer = parse_answer(state.output.completion, len(board.word), alphabet)
        index = load_dictionary_index(wordlist_path)
        in_dictionary = answer in set(index.get(len(answer), []))
        exact = answer == board.word
        consistent = exact or is_consistent(answer, board)
        return Score(
            value={
                "exact": float(exact),
                "consistent": float(consistent),
                "in_dictionary": float(in_dictionary),
            },
            answer=answer,
            explanation=(
                f"board {board.render()} excluded [{', '.join(board.excluded)}] "
                f"target {board.word} answer {answer!r}"
            ),
            metadata={"raw_completion": state.output.completion},
        )

    return score


# --------------------------------------------------------------------------
# Task
# --------------------------------------------------------------------------


def build_prompt(
    board: PinnedBoard,
    language: str = Language.ENGLISH.value,
    style: BoardStyle = "spaced",
    told_unique: bool = False,
) -> str:
    """The single prompt a board is shown as.

    ``told_unique`` adds the fact that exactly one word fits. In the game the
    model is never told this, so the default leaves it out; the flag exists to
    measure how much of the failure is not knowing the board is decisive.
    """
    excluded = ", ".join(board.excluded) if board.excluded else "none"
    ask = (
        "Exactly one word fits. Reply with that word only."
        if told_unique
        else "What is the word? Reply with the single most likely word only."
    )
    return (
        f"You are playing Hangman in {language}. "
        f"The board shows '_' for letters not yet revealed.\n"
        f"Board: {board.render(style)}\n"
        f"Letters already guessed that are not in the word: {excluded}\n"
        f"The word has {len(board.word)} letters. {ask}"
    )


@task
def pinned_probe(
    boards: str | None = None,
    source: str | None = None,
    n: int = 300,
    seed: int | None = 0,
    extra_wrong: int = 0,
    board_style: str = "spaced",
    told_unique: bool = False,
    language: str = Language.ENGLISH.value,
    wordlist: str | None = None,
) -> Task:
    """Name the word from a board that already determines it.

    Args:
        boards: TSV of boards (word, board, excluded, source, zipf_band), as
            written by analysis/pinned_boards.py. Generated from the
            dictionary when omitted.
        source: Keep only boards with this ``source`` value from the TSV
            (for example ``pilot`` or ``dictionary``).
        n: Boards to generate when no TSV is given.
        seed: Seed for generation. None draws a fresh seed and records it in
            every sample's metadata, so the run is reproducible afterwards
            without a canonical list to memorise.
        extra_wrong: Extra excluded letters added to generated boards.
        board_style: ``spaced`` (the game's rendering) or ``contiguous``.
        told_unique: Tell the model that exactly one word fits.
        language: Language of the words.
        wordlist: Dictionary for generation and scoring; defaults to the one
            shipped with the package.
    """
    if board_style not in ("spaced", "contiguous"):
        raise ValueError("board_style must be 'spaced' or 'contiguous'")
    style: BoardStyle = "spaced" if board_style == "spaced" else "contiguous"
    lang = Language(language.lower())
    wordlist_path = str(resolve_wordlist(wordlist))

    if boards is not None:
        items = read_boards(pathlib.Path(boards))
        if source is not None:
            items = [b for b in items if b.source == source]
        if not items:
            raise ValueError(
                f"No boards in {boards}" + (f" with source={source}" if source else "")
            )
        used_seed = None
    else:
        used_seed = seed if seed is not None else random.SystemRandom().randrange(2**32)
        index = load_dictionary_index(wordlist_path)
        items = sample_pinned_boards(index, n=n, seed=used_seed, extra_wrong=extra_wrong)

    samples = [
        Sample(
            id=f"{b.source or 'dictionary'}:{b.word}:{b.board}:{b.excluded}",
            input=build_prompt(b, lang.value, style, told_unique),
            target=b.word,
            metadata={
                "word": b.word,
                "board": b.board,
                "excluded": b.excluded,
                "source": b.source or "dictionary",
                "zipf_band": b.zipf_band,
                "length": len(b.word),
                "n_excluded": len(b.excluded),
                "revealed_fraction": round(b.revealed_fraction, 3),
                "board_style": style,
                "told_unique": told_unique,
                "seed": used_seed,
                "language": lang.value,
            },
        )
        for b in items
    ]
    return Task(
        dataset=MemoryDataset(samples),
        solver=generate(),
        scorer=probe_scorer(wordlist=wordlist),
    )
